### ISSUE TITLE
Error when using install ffcv using guidance command.

### ISSUE THREAD

**Issue by HaoKang-Timmy** [libffcv/ffcv#272]
Hi, I am trying to install ffcv on my server.
Here are the server settings.
```
Platform:amd-linux
GPU: 1*RTX02080Ti
```
When I use the default code to create the environment, and set up the environment, I could not move data to gpu and an error occurred.
Here is the error:
```
Torch not compiled with CUDA enabled
```
I have installed GPU driver on my server. Could you please tell me why this happens?

**Comment by Morales97** [comment]
Same issue here, `torch.cuda.is_available()` will return `False` in the conda env where I installed ffcv, while I can use GPU normally in any other environment. 

My conda env was created following the instructions as
`conda create -y -n ffcv python=3.9 cupy pkg-config compilers libjpeg-turbo opencv pytorch torchvision cudatoolkit=11.3 numba -c pytorch -c conda-forge`. Then I installed ffcv with `pip install ffcv`.

**Comment by andrewilyas** [comment]
Hi! What versions of CUDA do you have installed? And what does ``torch.__version__`` return?

**Comment by arnaghosh** [comment]
Hi @andrewilyas,

I was having the same problem. 
`torch.__version__` returns 1.13.1.
Would you recommend installing torch 1.10 instead (this was a previous configuration for which ffcv worked for me)

Thanks in advance!

**Comment by dngfra** [comment]
I had the same issue creating the conda env using the instructions. This env seems to work for me `conda create -y -n ffcv python=3.9 cupy pkg-config compilers libjpeg-turbo opencv pytorch torchvision torchaudio pytorch-cuda=11.7 numba -c pytorch -c conda-forge -c nvidia`

**Comment by arnaghosh** [comment]
Thanks for the update @dngfra, it seems that the issue was a mismatch between pytorch and cuda versions.
